### ISSUE TITLE
checkHex(byte currentNo error

### ISSUE THREAD

**Issue by shura-2** [satspares/DWIN_DGUS_HMI#2]
ошибка в функции 

String DWIN::checkHex(byte currentNo){

    if (currentNo < 10){
        return "0"+String(currentNo, HEX);   
    }
    
    return String(currentNo, HEX);
}

Вместо  if (currentNo < 10){   должно быть  if (currentNo < 16){

В противном случае 

void onHMIEvent(String address, int lastByte, String message, String response) 

response вместо 0А выдает А

**Comment by satspares** [comment]
Hello checkHex already has 0x10  in it which is 16 dec
if (currentNo < 0x10)
This is one of the problems I fixed from the dwin version.
Are you using my version?

Looking back this was fixed by commit 5a924d8 on the 7th July.
If you are using an old version you should upgrade.
